name: Murder Drones Download Tool (mddt)
version: '1.0'
base: core20
summary: A command-line tool for downloading Murder Drones episodes.
description: MDDT can be used to download any quality of every episode in the Murder Drones series, or you can even download the series in every quality!
confinement: strict

apps:
  mddt:
    command: mddt
    plugs: [home, network]

parts:
  mddt:
    plugin: nil
